server:
  port: 8080
  contextPath: /api
stlcourts:
  citationDataSources:
    tyler:
      rootURL: TODO
      apiKey: TODO
---
spring:
  profiles.active: local
---
spring:
  profiles: local
stlcourts:
  clientURL: http://localhost:9000
  security:
    municipalitySalt: salt1
    judgeSalt: salt2
    courtSalt: salt3
---
spring:
  profiles: qa
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  clientURL: http://test.yourstlcourts.com
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
---
spring:
  profiles: prod
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  clientURL: http://www.yourstlcourts.com
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}