server:
  port: 8080
  contextPath: /api
management:
  context-path: /manage
  port: -1
stlcourts:
  citationDataSources:
    tyler:
      rootUrl: http://TODOURL/api/citations
      apiKey: TODOKEY
  twilio:
    accountSid: ${TWILIO_SID}
    authToken: ${TWILIO_AUTH_TOKEN}
    phoneNumber: +13142548050
---
spring:
  profiles.active: local
---
spring:
  profiles: local
stlcourts:
  citationDataSources:
    testEnabled: true
    liveEnabled: true
  clientURL: http://localhost:9000
  demoMode: true
  runHeadless: true
  security:
    municipalitySalt: salt1
    judgeSalt: salt2
    courtSalt: salt3
management:
  port: 8080
---
spring:
  profiles: localWithHSQLAccess
  clientURL: http://localhost:9000
stlcourts:
  citationDataSources:
    testEnabled: true
    liveEnabled: false
  clientURL: http://localhost:9000
  demoMode: true
  runHeadless: false
  security:
    municipalitySalt: salt1
    judgeSalt: salt2
    courtSalt: salt3
---
spring:
  profiles: qa
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  citationDataSources:
    testEnabled: ${TEST_SOURCES_ENABLED}
    liveEnabled: ${LIVE_SOURCES_ENABLED}
  clientURL: http://test.yourstlcourts.com
  demoMode: false
  runHeadless: true
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
---
spring:
  profiles: prod
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  citationDataSources:
    testEnabled: false
    liveEnabled: true
  clientURL: http://www.yourstlcourts.com
  demoMode: false
  runHeadless: true
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}