server:
  port: 8080
  contextPath: /api
management:
  context-path: /manage
  port: -1
stlcourts:
  citationDataSources:
    tyler:
      rootUrl: http://TODOURL/api/citations
      apiKey: TODOKEY
---
spring:
  profiles.active: local
---
spring:
  profiles: local
twilio:
  accountSid: ${TWILIO_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: +13142548050
stlcourts:
  citationDataSources:
    testEnabled: true
    liveEnabled: true
  clientURL: http://localhost:9000
  security:
    municipalitySalt: salt1
    judgeSalt: salt2
    courtSalt: salt3
    demoModeAllowed: true
management:
  port: 8080
---
spring:
  profiles: localWithHSQLAccess
  clientURL: http://localhost:9000
twilio:
  accountSid: ${TWILIO_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: +13142548050
stlcourts:
  security:
    municipalitySalt: salt1
    judgeSalt: salt2
    courtSalt: salt3
    demoModeAllowed: true
---
spring:
  profiles: qa
twilio:
  accountSid: ${TWILIO_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: +13142548050
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  citationDataSources:
    testEnabled: ${TEST_SOURCES_ENABLED}
    liveEnabled: ${LIVE_SOURCES_ENABLED}
  clientURL: http://test.yourstlcourts.com
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
    demoModeAllowed: true
---
spring:
  profiles: prod
twilio:
  accountSid: ${TWILIO_SID}
  authToken: ${TWILIO_AUTH_TOKEN}
  phoneNumber: +13142548050
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  citationDataSources:
    testEnabled: false
    liveEnabled: true
  clientURL: http://www.yourstlcourts.com
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
    demoModeAllowed: false