server:
  port: 8080
  contextPath: /api

management:
  context-path: /manage
  port: -1

stlcourts:
  citationDataSources:
    tyler:
      rootUrl: ${TYLER_ROOT_URL}
      apiKey: ${TYLER_API_KEY}
    rejis:
      rootUrl: ${REJIS_ROOT_URL}
      username: ${REJIS_USERNAME}
      password: ${REJIS_PASSWORD}
    imported:
      rootUrl: ${IMPORTED_ROOT_URL}

logging:
  level:
    root: 'WARN'
    org.springframework.http.client: 'OFF'
    org.springframework.web.client: 'OFF'
    sun.net.www.protocol.http: 'OFF'

---
spring:
  profiles.active: local
  cache:
    cache-names: courtsById,courtsByMunicipalityId,allCourts
    caffeine:
      spec: expireAfterWrite=86400s
---
spring:
  profiles: local
stlcourts:
  citationDataSources:
    testEnabled: true
    liveEnabled: true
  clientURL: http://localhost:9000
  demoMode: true
  runHeadless: true
  security:
    municipalitySalt: salt1
    judgeSalt: salt2
    courtSalt: salt3
  twilio:
    accountSid: ${TWILIO_SID}
    authToken: ${TWILIO_AUTH_TOKEN}
    phoneNumber: ${TWILIO_PHONE_NUMBER}
management:
  port: 8080
---
spring:
  profiles: localWithHSQLAccess
stlcourts:
  citationDataSources:
    testEnabled: true
    liveEnabled: true
  clientURL: http://localhost:9000
  demoMode: true
  runHeadless: false
  security:
    municipalitySalt: salt1
    judgeSalt: salt2
    courtSalt: salt3
  twilio:
    accountSid: ${TWILIO_SID}
    authToken: ${TWILIO_AUTH_TOKEN}
    phoneNumber: ${TWILIO_PHONE_NUMBER}
---
spring:
  profiles: qa
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  citationDataSources:
    testEnabled: ${TEST_SOURCES_ENABLED}
    liveEnabled: ${LIVE_SOURCES_ENABLED}
  clientURL: http://test.yourstlcourts.com
  demoMode: true
  runHeadless: true
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
  twilio:
    accountSid: ${TWILIO_SID}
    authToken: ${TWILIO_AUTH_TOKEN}
    phoneNumber: ${TWILIO_PHONE_NUMBER}
---
spring:
  profiles: prod
spring.datasource:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql:${MYSQL_URL}?useUnicode=true&amp;characterEncoding=UTF-8
  username: ${MYSQL_USERNAME}
  password: ${MYSQL_PASSWORD}
  testWhileIdle: true
  timeBetweenEvictionRunsMillis: 60000
  validationQuery: SELECT 1
stlcourts:
  citationDataSources:
    testEnabled: false
    liveEnabled: true
  clientURL: http://www.yourstlcourts.com
  demoMode: false
  runHeadless: true
  security:
    municipalitySalt: ${MUNICIPALITY_SALT}
    judgeSalt: ${JUDGE_SALT}
    courtSalt: ${COURT_SALT}
  twilio:
    accountSid: ${TWILIO_SID}
    authToken: ${TWILIO_AUTH_TOKEN}
    phoneNumber: ${TWILIO_PHONE_NUMBER}